# Generated by Django 4.2.19 on 2025-03-12 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConditionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ObservationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('birthDate', models.DateField(blank=True, null=True)),
                ('familyName', models.CharField(blank=True, max_length=20, null=True)),
                ('givenName', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ObservationQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=20, null=True)),
                ('timestamp', models.DateTimeField()),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations_quality', to='bpapp.observationtype')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations_quality', to='bpapp.patient')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ObservationConcept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=50, null=True)),
                ('timestamp', models.DateTimeField()),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations_concept', to='bpapp.observationtype')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations_concept', to='bpapp.patient')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CVDPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probability', models.FloatField(blank=True, null=True)),
                ('model_version', models.CharField(blank=True, max_length=50, null=True)),
                ('explanation', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CVDPrediction', to='bpapp.patient')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinical_status', models.CharField(choices=[('active', 'Active'), ('recurrence', 'Recurrence'), ('relapse', 'Relapse'), ('inactive', 'Inactive'), ('remission', 'Remission'), ('resolved', 'Resolved')], default='active', max_length=20)),
                ('timestamp', models.DateTimeField()),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='bpapp.conditiontype')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='bpapp.patient')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
