# Generated by Django 4.2.19 on 2025-03-13 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='jsonFilePath',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
